plot4 <- function(){
      epc <- read.csv("household_power_consumption.txt", sep = ";", header = TRUE)
      epcFiltered <- epc[epc$Date == "1/2/2007" | epc$Date == "2/2/2007", ]
      epcFiltered$Datetime <- strptime(paste(epcFiltered$Date, epcFiltered$Time), format = "%d/%m/%Y %H:%M:%S")
      epcFiltered$Global_active_power <- as.numeric(as.character(epcFiltered$Global_active_power))
      epcFiltered$Global_reactive_power <- as.numeric(as.character(epcFiltered$Global_reactive_power))
      epcFiltered$Voltage <- as.numeric(as.character(epcFiltered$Voltage))
      epcFiltered$Sub_metering_1 <- as.numeric(as.character(epcFiltered$Sub_metering_1))
      epcFiltered$Sub_metering_2 <- as.numeric(as.character(epcFiltered$Sub_metering_2))
      epcFiltered$Sub_metering_3 <- as.numeric(as.character(epcFiltered$Sub_metering_3))
      png(file = "plot4.png")
      par(mar=c(4,4,1,2))
      par(mfrow = c(2,2))
      plot(epcFiltered$Datetime, epcFiltered$Global_active_power, type="n", xlab="", ylab="Global Active Power")
      lines(epcFiltered$Datetime, epcFiltered$Global_active_power)
      plot(epcFiltered$Datetime, epcFiltered$Voltage, type="n", xlab="datetime", ylab="Voltage")
      lines(epcFiltered$Datetime, epcFiltered$Voltage)
      plot(epcFiltered$Datetime, epcFiltered$Sub_metering_1, type="n", xlab="", ylab="Energy sub metering")
      lines(epcFiltered$Datetime, epcFiltered$Sub_metering_1)
      lines(epcFiltered$Datetime, epcFiltered$Sub_metering_2, col=c("red"))
      lines(epcFiltered$Datetime, epcFiltered$Sub_metering_3, col=c("blue"))
      legend("topright", c("Sub_metering_1","Sub_metering_2", "Sub_metering_3"), lty=c(1,1,1), lwd=c(1,1,1),col=c("black","blue","red"), bty="n")
      plot(epcFiltered$Datetime, epcFiltered$Global_reactive_power, type="n", xlab="datetime", ylab="Global_rective_power")
      lines(epcFiltered$Datetime, epcFiltered$Global_reactive_power)
      dev.off()
}